// Package ferrule is the module root. It holds nothing but the guide: go:embed cannot
// reach above its own directory, and docs/ has to live at the root because GitHub Pages
// serves it from there. Embedding it here lets the daemon serve the same files at /guide/,
// so the guide is in the binary and "one binary" stays literally true.
package ferrule

import "embed"

// Guide is docs/ as it ships: the page, its captures, its fonts. Regenerated by
// docs/regenerate.sh from the build; never edited by hand. The patterns name the files
// the page needs and nothing else, so the generator itself stays out of the binary.
//
//go:embed docs/index.html docs/fonts docs/screenshots docs/transcripts
var Guide embed.FS
